USE ROLE TRAINING_ROLE;
CREATE WAREHOUSE IF NOT EXISTS KANGAROO_WH;
USE WAREHOUSE KANGAROO_WH;

SHOW WAREHOUSES;
ALTER WAREHOUSE KANGAROO_WH RESUME;

-- Vytvorenie databazy
CREATE DATABASE IF NOT EXISTS KANGAROO_NORTHWIND_DB;
USE KANGAROO_NORTHWIND_DB;

-- Vytvorenie schemy pre staging tabulky
CREATE SCHEMA IF NOT EXISTS KANGAROO_NORTHWIND_DB.STAGING;

-- Pouzitie schemy
USE SCHEMA KANGAROO_NORTHWIND_DB.STAGING;


